### ISSUE TITLE
Not working on Mac OS high Sierra

### ISSUE THREAD

**Issue by kentuck13** [mallowigi/dracula-theme-jetbrains#2]
**Describe the bug**
Not working on Mac OS high Sierra, PyCharm 2018.

**To Reproduce**
1. install package via Settings > Plugins
2. Restart PyCharm
3. Can't open any project.

**Comment by mallowigi** [comment]
I am working on Mac and didn't see any problems. Which plugins do you use? And can you post the logs ?
